name: 'Create GAP release'
description: 'blah blah yada yada'

runs:
  using: "composite"
  steps:
      - name: "Install TeXLive packages"
        shell: bash
        run: |
          sudo apt update
          sudo apt-get install --no-install-recommends --yes texlive-latex-base texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended
      - name: "Setup GithubPagesForGAP"
        shell: bash
        run: |
          # Checkout existing branch if it exists, otherwise create (?)
          git fetch
          if ! git branch gh-pages origin/gh-pages then
            git remote add -f gh-gap https://github.com/gap-system/GitHubPagesForGAP
            git branch gh-pages gh-gap/gh-pages --no-track
            git worktree add gh-pages gh-pages
            cd gh-pages
            git commit -m "Setup gh-pages based on GitHubPagesForGAP"
            git push --set-upstream origin gh-pages
            cd ../
          else 
            git worktree add gh-pages gh-pages
          fi
      - name: "Setup Releasetools"
        shell: bash
        run: |
          mkdir $HOME/ReleaseTools
          wget https://github.com/gap-system/ReleaseTools/archive/refs/heads/master.tar.gz -O $HOME/ReleaseTools/ReleaseTools.tar.gz
          tar -xzf $HOME/ReleaseTools/ReleaseTools.tar.gz -C $HOME/ReleaseTools --strip-components=1
      - name: "Release"
        shell: bash
        run: |
          $HOME/ReleaseTools/release-gap-package
